import { Button, Container } from "@mui/material";
import { signIn } from "next-auth/react";
import Head from "next/head";
import Header from "~/components/Header";

export default function Home() {
  const signIntWithGoogle = async () => {
    await signIn("google");
  };

  return (
    <>
      <Head>
        <title>Meds stacker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Container component="main">
        <Button variant="contained" onClick={() => signIntWithGoogle}>
          Login
        </Button>
      </Container>
    </>
  );
}
